### ISSUE TITLE
 TS error: Only a void function can be called with the 'new' keyword.ts(2350) 

### ISSUE THREAD

**Issue by ganeshpatro321** [cedrickchee/react-typescript-jest-enzyme-testing#1]
![Screenshot from 2019-03-24 17-11-14](https://user-images.githubusercontent.com/30416891/54878861-45675800-4e58-11e9-91d0-dc40487d8aca.png)

@cedrickchee Can you help me with this?

**Comment by kamilmoskal** [comment]
@ganeshpatro321 you must install @types/enzyme-adapter-react-16
